### PR TITLE
Failed to connect to camera service

### PR DESCRIPTION
**Pull request by LaBoss**
On some devices even with permissions the terminal gives "Failed to connect to camera service" error and all application goes down

### CODE REVIEW

**Comment by JimmyPun610** [comment]
Hi @LaBoss,
I added your code. Thank you for you contribution.
May I have the information about the device model or brand? and what is the exact exception message?

**Comment by LaBoss** [comment]
Hello of course yes,

The device is: https://www.alibaba.com/product-detail/Portable-Handheld-pda-barcode-scanner-and_60716250256.html

Is a Chinese PDA... must have camera stack poorly implemented as most barcode scanning applications do not work. The permissions are given!

The full stacktrace is:

`Java.Lang.RuntimeException: Fail to connect to camera service
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <f8a5ef81e6f64091812a7da2968fba8c>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <f8a5ef81e6f64091812a7da2968fba8c>:0 
  at Android.Gms.Vision.CameraSource.Start (Android.Views.ISurfaceHolder surfaceHolder) [0x00036] in <271dcc70671b4ff49bf2c5e0127b2f8f>:0 
  at GoogleVisionBarCodeScanner.Droid.CameraPreview+SurfaceHolderCallback.SurfaceCreated (Android.Views.ISurfaceHolder holder) [0x00002] in F:\Projectos\GIT\BarcodeScanner.XF.git\GoogleVisionBarCodeScanner.Droid\CameraPreview.cs:209 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Fail to connect to camera service
	at android.hardware.Camera.<init>(Camera.java:643)
	at android.hardware.Camera.open(Camera.java:491)
	at com.google.android.gms.vision.CameraSource.zza(Unknown Source)
	at com.google.android.gms.vision.CameraSource.start(Unknown Source)
	at crc64dc2c891ba1b9bf87.CameraPreview_SurfaceHolderCallback.n_surfaceCreated(Native Method)
	at crc64dc2c891ba1b9bf87.CameraPreview_SurfaceHolderCallback.surfaceCreated(CameraPreview_SurfaceHolderCallback.java:47)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:709)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:180)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2558)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1467)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7062)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:644)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
`

**Comment by JimmyPun610** [comment]
Thank you.
I think there may be some problems on the camera. But it more likely about the specification on the Android OS.
How about can the device use default camera app or others camera app?
I think manufacturer had tuned the camera parts.

**Comment by LaBoss** [comment]
Hello, the default application I can use. 

Using this 
https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=pt_PT
works,

But this 
https://play.google.com/store/apps/details?id=com.google.zxing.client.android
dont work

**Comment by JimmyPun610** [comment]
Hi @LaBoss 
I think it is quite hard for me to test it without the device.
But the reason should be Android picking a wrong camera which is not functioning.
I am not sure how to fix it in this case.

**Pull request merged**
