### PR TITLE
Corner Points information

### PR DESCRIPTION
**Pull request by criistii**
Added information about corner points to the BarcodeResult. This should permit better control of selecting the appropriate barcode when multiple are present on screen. Can be used to draw the rectangle on screen.

### CODE REVIEW

**Comment by JimmyPun610** [comment]
This is a nice one, but I think the points coordination are needed to convert to Xamarin Form pointing system?

**Comment by criistii** [comment]
Will double check and get back with an update or feedback.

**Comment by criistii** [comment]
Done. Managed to map points to Forms coordinates.

**Comment by JimmyPun610** [comment]
cool. I will have a check and publish it asap. Thank you.

**Comment by JimmyPun610** [comment]
Just tried with Android and it looks the coordinate is wrong. Anyway, I will take a look when I have time

**Comment by JimmyPun610** [comment]
I found out that with updated CameraX, there is a function to convert ImageAnalyzer coordination to PreviewView coordination, I guess we could convert it to the correct Android coordination and then convert to Xamarin Forms. 

But the problem is the latest Xamarin Forms (5.0.0.2401) is not supported to that CameraX version, so I just keep it wrong at this moment and hopefully we could start to make it correct later (maybe in MAUI).

For iOS, I didn't start to look at it.


FYI
https://stackoverflow.com/questions/66583438/camerax-qrcode-scanner-detect-wrong
https://developer.android.com/reference/androidx/camera/view/transform/CoordinateTransform

**Pull request merged**
